level_1 = [
    "HHHHKAQ                 S",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "XP XXXXXXXE         XXXXX",
    "X  XXXXXXX  XXXXXX  XXXXX",
    "X       XX      XX  XXXXX",
    "X       XX  XXXX      EXX",
    "X XXXX  XX  XXX        XX",
    "X  CXX  XX  XXXXXX  XX XX",
    "XXXX X  XX    XXXX  XX XX",
    "XF X X        XXXXT XXBXX",
    "X  X X  XXXXXXXXXXXXXXXXX",
    "X         XXXXXX        X",
    "X                XX XXXXX",
    "XXXXXXX XXXX     XXBXX FX",
    "XXXXXXX    XX    XXXXX  X",
    "XXXF XXXXXXXXXX         X",
    "XXX           D         X",
    "XXX         XXXX   XXXXXX",
    "XXXXXXX XX  XXXXXXXXXXXXX",
    "XXXX    XX    E        FX",
    "XXT XXXXXX              X",
    "XE   XXXXXXXXX XXXXDXXXXX",
    "XX    XXXXXXT  XXX  XXXXX",
    "XX          XXXX        X",
    "XXXXCCB                NX",
    "XXXXXXXXXXXXXXXXXXXXXXXXX"
]

level_2 = [
    "HHHHKAQ                 S",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "XP XXXXXXXE       XXXXX X",
    "X      FXX  XXX         X",
    "X       XX  X       XXX X",
    "XXXX    XX  XXXXXX    EXX",
    "XT      XX  XXXE       XX",
    "XXXXXXDXXX  XXXXXX  XXXXX",
    "XXXXXX  XX    XXXXCTXXXXX",
    "XF XXX        XXXXXXXXXXX",
    "X  XXX  XXXXX         FXX",
    "X         XXXXXXXXXX XXXX",
    "X                XXT XXXX",
    "XXXXXX  XXXX     XXX X  X",
    "XXXXX      XXXX  XXXXX  X",
    "XXXF XXXXXXXXXX         X",
    "XXX           D         X",
    "XXX         XXXXXXXXXXXXX",
    "XXXX  XXXX  XXXXXXXXXXXXX",
    "XXXXX   XX              X",
    "XXBCTXX XX              X",
    "XX   XX XXXXXXXXXXXDXXXXX",
    "XX    X XXXXXXXXXX  XXXXX",
    "XX      X   XXXX        X",
    "XXXX    X E            NX",
    "XXXXXXXXXXXXXXXXXXXXXXXXX"
]

level_3 = [
    "HHHHKAQ                 S",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "XP                  XXXXX",
    "X  X   FXX  XX XXX     XX",
    "X  X    XX  XX XXX  XXXXX",
    "X XX X  XX  XXX       EXX",
    "XTX  X  XX  XXX        XX",
    "XXXXXXXXXX  XXXXXX  XXXXX",
    "XXXXXX  XX    XXXXDXXXXXX",
    "XF XXX        XXXXT    XX",
    "X  XXX  XXXXXXXTB XXXX XX",
    "X         XXXXXXXCC    XX",
    "X         X     FXXXXXXXX",
    "XX E      XXXX   XXXXX  X",
    "XX               XXXXX  X",
    "XXXXXXXXXXXXXXX         X",
    "XXX    E      D         X",
    "XCX         XXXXXXXXXXXXX",
    "X   XXXXXX  XXXXX  FXXXXX",
    "XXXXXXB                 X",
    "W    XX XX              X",
    "XX   XX XXXXX   XXXDXXXXX",
    "XX    XXXXXXXXXXXX  XXXXX",
    "XX    EE    XXXX        X",
    "XXXX                    X",
    "XXXXXXXXXXXXXXXXXXXXXXXXX"
]

level_4 = [
    "HHHHKAQ                 S",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "XPX                 E    X",
    "X X                     X",
    "X XXXDXXXXXXXFXXBXCXXXXDX",
    "X XXX XXXXXXXXXXXXXXXXX X",
    "X     FXT               X",
    "XXXXXXXXXXXXXXXXXXXXXX  X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
]

level_5 = [
    "HHHHKAQ                 S",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
]

level_6 = [
    "HHHHKAQ                 S",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
]

level_7 = [
    "HHHHKAQ                 S",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
]

level_8 = [
    "HHHHKAQ                 S",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
]

level_9 = [
    "HHHHKAQ                 S",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
]

level_final = [
    "HHHHKAQ                 S",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "X                       X",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
]

game_over_screen = [
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "  GGGG GGGG GG  GG GGGG  ",
    "  G    G  G GGGGGG G     ",
    "  G    G  G G GG G GGGG  ",
    "  G GG GGGG G    G G     ",
    "  G  G G  G G    G G     ",
    "  GGGG G  G G    G GGGG  ",
    "                         ",
    "                         ",
    "  GGGG G   G GGGG GGGG   ",
    "  G  G G   G G    G  G   ",
    "  G  G GG GG GGGG GGGG   ",
    "  G  G  G G  G    GG     ",
    "  G  G  G G  G    G G    ",
    "  GGGG   G   GGGG G  G   ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
]
